name: Update SonarQube Badges

permissions:
  contents: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Delete old badge images
        run: rm ./repo_images/sonarqube_badges/*.svg

      - name: Download coverage badge
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          curl "$SONAR_HOST_URL/api/project_badges/quality_gate?project=EPAM_python_task&token=$SONAR_TOKEN" \
            -o ./repo_images/sonarqube_badges/quality_gate.svg
          curl "$SONAR_HOST_URL/api/project_badges/measure?project=EPAM_python_task&metric=coverage&token=$SONAR_TOKEN" \
            -o ./repo_images/sonarqube_badges/coverage.svg
          curl "$SONAR_HOST_URL/api/project_badges/measure?project=EPAM_python_task&metric=duplicated_lines_density&token=$SONAR_TOKEN" \
            -o ./repo_images/sonarqube_badges/duplicated_lines_density.svg
          curl "$SONAR_HOST_URL/api/project_badges/measure?project=EPAM_python_task&metric=software_quality_reliability_issues&token=$SONAR_TOKEN" \
            -o ./repo_images/sonarqube_badges/software_quality_reliability_issues.svg
          curl "$SONAR_HOST_URL/api/project_badges/measure?project=EPAM_python_task&metric=software_quality_security_issues&token=$SONAR_TOKEN" \
            -o ./repo_images/sonarqube_badges/software_quality_security_issues.svg

      - name: Commit badges
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./repo_images/sonarqube_badges/*.svg
          git commit -m "Update SonarQube badges [skip ci]" || echo "No changes"
          git push
